version: '3'


services:



  ## --------------------------------------------
  ## | 8 : cache server
  ## --------------------------------------------
  redis:
    image: redis:4.0.10-alpine
    expose:
      - "6379"
    volumes:
      - ./docker/redis/default.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/data:/data
    ports:
      - "127.0.0.1:6379:6379"
    restart: always
    command: [
      "sh", "-c",
      '
       docker-entrypoint.sh
       --requirepass "bccstyle"
      '
    ]
