version: '3'


services:



#  ## --------------------------------------------
#  ## | 8 : cache server
#  ## --------------------------------------------
#  redis:
#    image: redis:4.0.10-alpine
#    expose:
#      - "6379"
#    volumes:
#      - ./docker/redis/default.conf:/usr/local/etc/redis/redis.conf
#      - ./docker/redis/data:/data
#    ports:
#      - "127.0.0.1:6379:6379"
#    restart: always
#    command: [
#      "sh", "-c",
#      '
#       docker-entrypoint.sh
#       --requirepass "bccstyle"
#      '
#    ]

  elasticsearch:
    build:
      context: ./docker/elasticsearch
      dockerfile: Dockerfile
      args:
        - UID=1000
        - GID=1000
    ports:
      - "127.0.0.1:9202:9200"
    environment:
      - cluster.name=irantalent
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx2g -Xms2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - ./docker/elasticsearch/data/:/usr/share/elasticsearch/data
    expose:
      - "9200"

