version: '3'


services:


  elasticsearch:
    build:
      context: ./docker/elasticsearch
      dockerfile: Dockerfile
      args:
        - UID=1000
        - GID=1000
    ports:
      - "127.0.0.1:9202:9200"
    environment:
      - cluster.name=irantalent
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx2g -Xms2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/elasticsearch/data/:/usr/share/elasticsearch/data
    expose:
      - "9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    volumes:
      - ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch

    environment:
      #      - ELASTICSEARCH_USERNAME=bccstyle
      #      - ELASTICSEARCH_PASSWORD=Arcsin_360
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5602:5601"
      -
  ## --------------------------------------------
  ## | 8 : cache server
  ## --------------------------------------------
  redis:
    image: redis:4.0.10-alpine
    expose:
      - "6379"
    volumes:
      - ./docker/redis/default.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "127.0.0.1:6379:6379"
    command: [
      "sh", "-c",
      '
       docker-entrypoint.sh
       --requirepass "bccstyle"
      '
    ]
