version: '3'


services:


  elasticsearch:
    build:
      context: ./docker/elasticsearch
      dockerfile: Dockerfile
      args:
        - UID=1000
        - GID=1000
    ports:
      - "0.0.0.0:9202:9200"
    environment:
      - cluster.name=irantalent
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx2g -Xms2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/elasticsearch/data/:/usr/share/elasticsearch/data
    expose:
        - "9200"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    expose:
      - '80'
      - '443'
    environment:
      - PMA_HOST=localhost
      - PMA_PORT=3306
#      - PMA_ARBITRARY=1
    volumes:
      - /sessions
    ports:
      - 8008:80
