version: '3'


services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    expose:
      - "80"
    ports:
      - 8009:80
    restart: always
    depends_on:
      - php
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    expose:
      - "9000"
    volumes:
      - ./:/var/www/html/
    ## --------------------------------------------
    ## | 4 : database server
    ## --------------------------------------------
  mysqldb:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=bccstyle
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_USER=nima
      - MYSQL_PASSWORD=123123
    expose:
      - "3306"
    ports:
      - "1212:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
      - ./vol-share/:/v-share/


  elasticsearch:
    build:
      context: ./docker/elasticsearch
      dockerfile: Dockerfile
      args:
        - UID=1000
        - GID=1000
    ports:
      - "127.0.0.1:9202:9200"
    environment:
      - cluster.name=irantalent
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx2g -Xms2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/elasticsearch/data/:/usr/share/elasticsearch/data
    expose:
        - "9200"


      ## --------------------------------------------
      ## | 7 : Kibana visualization
      ## --------------------------------------------
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    volumes:
      - ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch

    environment:
      #        - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      #        - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "127.0.0.1:5602:5601"