version: '3'


services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    expose:
      - "80"
    ports:
      - 80:80
    restart: always
    depends_on:
      - php
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    expose:
      - "9000"
    volumes:
      - ./:/var/www/html/
    ## --------------------------------------------
    ## | 4 : database server
    ## --------------------------------------------
  mysqldb:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=bccstyle
      - MYSQL_ROOT_PASSWORD=arcsin360
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_password
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
      - ./vol-share/:/v-share/
