<?php
namespace app\components;

use yii;
use yii\base\Component;

class Api extends Component
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function Call($method, $url, $data = false, $headers = false)
    {
        $curl = curl_init();
        if($headers)
            curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
        switch ($method)
        {
            case "POST":
                curl_setopt($curl, CURLOPT_POST, 1);

                if ($data)
                    curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
                break;
            case "GET":
                if ($data)
                    $url = $url + "?" + http_build_query($data);
                break;
            default:
                break;
        }
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        $result = curl_exec($curl);
        curl_close($curl);
        return $result;
    }

}
?>
