<?php
namespace app\components;

use Yii;
use yii\base\Component;
use yii\web\Response;
use yii\helpers\Json;


class Mellatbank extends Component
{

  public $terminalId	= "1987903";							//-- شناسه ترمینال
  public  $userName		= "bcc73"; 							//-- نام کاربری
  public $userPassword	= "99863608"; 

  public function init()
  {
      parent::init(); // TODO: Change the autogenerated stub
  }

  public function Request($amount,$callBackUrl){
    $amount*=10;
    $orderId		= rand();								//-- شناسه فاکتور
    $localDate		= date('Ymd');
    $localTime		= date('Gis');
    $additionalData	= "";
    $payerId		= 0;
    
    //-- تبدیل اطلاعات به آرایه برای ارسال به بانک
    $parameters = array(
      'terminalId' 		=> $this->terminalId,
      'userName' 			=> $this->userName,
      'userPassword' 		=> $this->userPassword,
      'orderId' 			=> $orderId,
      'amount' 			=> $amount,
      'localDate' 		=> $localDate,
      'localTime' 		=> $localTime,
      'additionalData' 	=> $additionalData,
      'callBackUrl' 		=> $callBackUrl,
      'payerId' 			=> $payerId
    );
    $client 	= new \nusoap_client('https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl');
    $namespace 	='http://interfaces.core.sw.bps.com/';
    $result 	= $client->call('bpPayRequest', $parameters, $namespace);

    
    //-- بررسی وجود خطا
    if ($client->fault)
    {
      //-- نمایش خطا
      die("خطا در اتصال به وب سرویس بانک");
    } else {
      $err = $client->getError();
    
      if ($err)
      {
        //-- نمایش خطا
        die($err);
      } else {
        $res 		= explode (',',$result);
        $ResCode 	= $res[0];
    
        if ($ResCode == "0")
        {
          //-- انتقال به درگاه پرداخت
          echo "<form name='myform' action='https://bpm.shaparak.ir/pgwchannel/startpay.mellat' method='POST'><input type='hidden' id='RefId' name='RefId' value='{$res[1]}'></form><script type='text/javascript'>window.onload = formSubmit; function formSubmit() { document.forms[0].submit(); }</script>";
        } else {
          //-- نمایش خطا
          die($result);
        }
      }
    }

  }
  public function Callback($post){
    $ResCode 		= (isset($post['ResCode']) && $post['ResCode'] != "") ? $post['ResCode'] : "";

    if ($ResCode == '0')
    {
      $client 				= new \nusoap_client('https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl');
      $namespace 				='http://interfaces.core.sw.bps.com/';
      $orderId 				= (isset($post['SaleOrderId']) && $post['SaleOrderId'] != "") ? $post['SaleOrderId'] : "";
      $verifySaleOrderId 		= (isset($post['SaleOrderId']) && $post['SaleOrderId'] != "") ? $post['SaleOrderId'] : "";
      $verifySaleReferenceId 	= (isset($post['SaleReferenceId']) && $post['SaleReferenceId'] != "") ? $post['SaleReferenceId'] : "";

      $parameters = array(
        'terminalId' 		=> $this->terminalId,
        'userName' 			=> $this->userName,
        'userPassword' 		=> $this->userPassword,
        'orderId' 			=> $orderId,
        'saleOrderId' 		=> $verifySaleOrderId,
        'saleReferenceId' 	=> $verifySaleReferenceId
      );

      $result = $client->call('bpVerifyRequest', $parameters, $namespace);

      if($result == 0){
        $result = $client->call('bpSettleRequest', $parameters, $namespace);

        if($result == 0){
          return true;
          //-- تمام مراحل پرداخت به درستی انجام شد.
       //   die("عملیات پرداخت با موفقیت انجام شد, شناسه پیگیری تراکنش : {$verifySaleReferenceId}");
        } else {
          $client->call('bpReversalRequest', $parameters, $namespace);			

          //-- نمایش خطا
          $error_msg = (isset($result) && $result != "") ? $result : "خطا در ثبت درخواست واریز وجه";
//          die($error_msg);
            return false;
        }
      } else {
        $client->call('bpReversalRequest', $parameters, $namespace);
        
        //-- نمایش خطا
        $error_msg = (isset($result) && $result != "") ? $result : "خطا در عملیات وریفای تراکنش";
//        die($error_msg);
          return false;
      }
    } else {
      //-- نمایش خطا
      $error_msg = (isset($ResCode) && $ResCode != "") ? $ResCode : "تراکنش ناموفق";
//      die($error_msg);
        return false;
    }
  }

}
