<?php
namespace app\components;

use yii;
use yii\base\Component;

class Payment extends Component
{

  public function init()
  {
      parent::init(); // TODO: Change the autogenerated stub
  }


  public function melli_request($Amount,$OrderId,$ReturnUrl){
    
      $key 			= "ZnbfBM4AbkL7bMBM4yNEFR8zdtHw4r1F";
      $MerchantId 	= "000000140331149";
      $TerminalId 	= "24051005";
      $LocalDateTime=date("m/d/Y g:i:s a");
      $Amount*=10;
      $SignData=$this->encrypt_pkcs7("$TerminalId;$OrderId;$Amount","$key");
      $data = array('TerminalId'=>$TerminalId,
                    'MerchantId'=>$MerchantId,
                    'Amount'=>$Amount,
                    'SignData'=> $SignData,
                    'ReturnUrl'=>$ReturnUrl,
                    'LocalDateTime'=>$LocalDateTime,
                    'OrderId'=>$OrderId);
      $str_data = json_encode($data);
      $res=$this->CallAPI('https://sadad.shaparak.ir/vpg/api/v0/Request/PaymentRequest',$str_data);
      $arrres=json_decode($res);
      
      if($arrres->ResCode==0)
      {
        $Token= $arrres->Token;
        $url="https://sadad.shaparak.ir/VPG/Purchase?Token=$Token"; 
       return \Yii::$app->getResponse()->redirect($url); 
      }
      else
        die($arrres->Description);  
  }
  public function melli_callback($OrderId="",$Token="",$ResCode=""){ 
      $key 		= "ZnbfBM4AbkL7bMBM4yNEFR8zdtHw4r1F";  
      if($ResCode==0)
      {
        $verifyData = array('Token'=>$Token,'SignData'=>$this->encrypt_pkcs7($Token,$key));
        $str_data = json_encode($verifyData);				
        $res=$this->CallAPI('https://sadad.shaparak.ir/vpg/api/v0/Advice/Verify',$str_data);
        $arrres=json_decode($res);

      }
      // var_dump($arrres);
      if(isset($arrres) && $arrres->ResCode!=-1 && $ResCode==0)
      {
        //Save $arrres->RetrivalRefNo,$arrres->SystemTraceNo,$arrres->OrderId to DataBase
        return ['status'=>1,'data'=>['referCode'=>$arrres->SystemTraceNo,'refrenceCode'=>$arrres->RetrivalRefNo,'orderId'=>$OrderId]];
        // echo "شماره سفارش:".$OrderId."<br>"."شماره پیگیری : ".$arrres->SystemTraceNo."<br>"."شماره مرجع:".
        // $arrres->RetrivalRefNo."<br> اطلاعات بالا را جهت پیگیری های بعدی یادداشت نمایید."."<br>";
      }
      else
      return ['status'=>0,'data'=>null];

        // echo "تراکنش نا موفق بود در صورت کسر مبلغ از حساب شما حداکثر پس از 72 ساعت مبلغ به حسابتان برمی گردد.";	
  }
  ///melat bank
  public function Request($price,$callback){
    $price*=10;
    $mellatbank = new \mihandev\gateway\MellatBank();
    return $mellatbank->startPayment([
        'terminal' => 1987903,
        'username' => 'bcc73',
        'password' => '99863608',
        'amount' => $price,
        'callBackUrl' => [$callback]
    ]);
  }
  public function Callback($post){
    $mellatbank = new \mihandev\gateway\MellatBank();
     $config = [
       'terminal' => 1987903,
       'username' => 'bcc73',
       'password' => '99863608',
       'amount' =>   \yii::$app->session['amount'],
     ];
     $result = $mellatbank->checkPayment($config,$post);
    
     if($result !== null && $result["status"] == "success") {
        \yii::$app->session['ref_code']=$result["trans"];
        return true;
     }else{
       return false;
     }
  }

  public function encrypt_pkcs7($str, $key)
  {
      $key = base64_decode($key);
      $ciphertext = OpenSSL_encrypt($str,"DES-EDE3", $key, OPENSSL_RAW_DATA);
      return base64_encode($ciphertext);
  }
  //Send Data
  public function CallAPI($url, $data = false)
  {
      $curl = curl_init($url);
      curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");  
      curl_setopt($curl, CURLOPT_POSTFIELDS,$data);
      curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
      curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type: application/json','Content-Length: ' . strlen($data)));
      $result = curl_exec($curl);
      curl_close($curl);
      return $result;
  }


  
  
  
}

// public function Request($price,$callback){

//   $mellatbank = new \mihandev\gateway\MellatBank();
//   return $mellatbank->startPayment([
//       'terminal' => 1987903,
//       'username' => 'bcc73',
//       'password' => '61522295',
//       'amount' => $price,
//       'callBackUrl' => [$callback]
//   ]);
// }

// public function Callback($post){
//   $mellatbank = new \mihandev\gateway\MellatBank();
//    $config = [
//      'terminal' => 1987903,
//      'username' => 'bcc73',
//      'password' => '61522295',
//        'amount' =>   yii::$app->session['amount'],
//    ];
//    $result = $mellatbank->checkPayment($config, $post);

//    if($result !== null && $result["status"] == "success") {
//       \yii::$app->session['ref_code']=$result["trans"];
//       return true;
//    }else{
//      return false;
//    }
// }

  // public function Request($bank=null,$data){
  //   switch ($bank) {
  //     case "mellat":
  //         return $this->mellat_request($data['orderId']);
  //         break;
  //     default:
  //         return $this->melli_request($data['amount'],$data['orderId'],$data['callBack']);
  //   }
  // }
  // public function Callback($bank=null, $data){
  //   switch ($bank) {
  //     case "mellat":
  //         return $this->mellat_callback($data['orderId']);
  //         break;
  //     default:
  //         return $this->melli_callback($data['orderId'],$data['token'],$data['resCode']);
  //   }
  // }

  // public function Request($amount,$callback){

  //   $amount = $amount; // Rial
  //   $callBackUrl = $callback; // callback url
  //   /* @var $mellatbank \ahmadrezaei\yii\mellatbank\components\Mellatbank */
  //   $mellatbank = Yii::$app->mellatbank;
  //   $mellatbank->createPayment($amount, $callBackUrl);
  // }
  // public function Callback(){

  //   $mellatbank = Yii::$app->mellatbank;
  //   $result = $mellatbank->verify();
  //   if( $result ) {
  //       // payment is successfull
  //       $transactionID = $mellatbank->transactionId;
  //       $resCode = $mellatbank->resultCode;
  //   } else {
  //       // payment is unsuccessfull
  //       $resCode = $mellatbank->resultCode;
  //   }
  // }
  // public function Request($price,$callback){

  //   $mellatbank = new \mihandev\gateway\MellatBank();
  //   return $mellatbank->startPayment([
  //       'terminal' => 1987903,
  //       'username' => 'bcc73',
  //       'password' => '61522295',
  //       'amount' => $price,
  //       'callBackUrl' => [$callback]
  //   ]);
  // }

  // public function Callback($post){
  //   $mellatbank = new \mihandev\gateway\MellatBank();
  //    $config = [
  //      'terminal' => 1987903,
  //      'username' => 'bcc73',
  //      'password' => '61522295',
  //        'amount' =>   yii::$app->session['amount'],
  //    ];
  //    $result = $mellatbank->checkPayment($config, $post);

  //    if($result !== null && $result["status"] == "success") {
  //       \yii::$app->session['ref_code']=$result["trans"];
  //       return true;
  //    }else{
  //      return false;
  //    }
  // }
