<?php
namespace app\components;

use Yii;
use yii\base\Component;
use yii\web\Response;
use yii\helpers\Json;


class Zarinpal extends Component
{
  public function init()
  {
      parent::init(); // TODO: Change the autogenerated stub
  }
  public function Request($Amount,$Mobile,$CallbackURL)
  {
    $MerchantID = '2ba8e896-6b15-11e9-9d52-000c29344814'; //Required   
    $Description = 'پرداخت از درگاه زرین پال'; // Required  
    $Email = 'UserEmail@Mail.Com'; // Optional 
    // $Mobile = '09123456789'; // Optional
    // $CallbackURL = 'http://www.yoursoteaddress.ir/verify.php'; // Required
    
    
    //$client = new \SoapClient('https://www.zarinpal.com/pg/services/WebGate/wsdl', ['encoding' => 'UTF-8']);
    $client = new \SoapClient('https://sandbox.zarinpal.com/pg/services/WebGate/wsdl', ['encoding' => 'UTF-8']);

    
    $result = $client->PaymentRequest(
    [
    'MerchantID' => $MerchantID,
    'Amount' => $Amount,
    'Description' => $Description,
    'Email' => $Email,
    'Mobile' => $Mobile,
    'CallbackURL' => $CallbackURL,
    ]
    );


    //Redirect to URL You can do it also by creating a form
    if ($result->Status == 100) {
      //\Yii::$app->getResponse()->redirect('https://www.zarinpal.com/pg/StartPay/'.$result->Authority);
      \Yii::$app->getResponse()->redirect('https://sandbox.zarinpal.com/pg/StartPay/'.$result->Authority);

    //برای استفاده از زرین گیت باید ادرس به صورت زیر تغییر کند:
    //Header('Location: https://www.zarinpal.com/pg/StartPay/'.$result->Authority.'/ZarinGate');
    } else {
    echo'ERR: '.$result->Status;
    }
 
  }
  public function Callback($Amount,$Authority){
    $MerchantID = '2ba8e896-6b15-11e9-9d52-000c29344814'; //Required
    //$Authority=\yii::$app->reuqest->get('Authority'); 
    
   // $client = new \SoapClient('https://www.zarinpal.com/pg/services/WebGate/wsdl', ['encoding' => 'UTF-8']);
    $client = new \SoapClient('https://sandbox.zarinpal.com/pg/services/WebGate/wsdl', ['encoding' => 'UTF-8']);
    
    $result = $client->PaymentVerification(
    [
    'MerchantID' => $MerchantID,
    'Authority' => $Authority,
    'Amount' => $Amount,
    ]);
  $Status = $result->Status;
  $RefID = $result->RefID;

    //var_dump($_GET['Status']);exit;
    if ($result->Status == 100) {
    echo 'Transaction success. RefID:'.$result->RefID;
    return true;
    } else {
 echo 'Transaction failed. Status:'.$result->Status;
    return false;
    }
    // } else {
    // // echo 'Transaction canceled by user';
    // return false;
    // }
  }

  // public function getStatus()
  // {
  //     return $this->_status;
  // }

  // public function getRefId() {
  //     return $this->_ref_id;
  // }
}