
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
#   - "./rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
 
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['0.0.0.0:9090']

  - job_name: 'grafana'
    static_configs:
    - targets: ['grafana:3000']

  - job_name: 'nginx_monitor'
    scrape_interval: 1m
    metrics_path: '/prometheus/'
    static_configs:
    - targets: ['nginx_monitor:9113']

  - job_name: cadvisor
    scrape_interval: 10s
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'host_control'
    scrape_interval: 10s
    static_configs:
    - targets: ['host_monitor:9100']

  - job_name: 'postgresql_control'
    scrape_interval: 10s
    static_configs:
    - targets: ['postgres_monitor:9187']

  - job_name: 'redis_monitor'
    scrape_interval: 10s
    static_configs:
    - targets: ['projects_redis-exporter_1:9121']

